#ifndef EP_PLATFORM_CAPABILITY_H
#define EP_PLATFORM_CAPABILITY_H

typedef enum {
    EP_PLATFORM_CAPABILITY_FILESYSTEM = 0,
    EP_PLATFORM_CAPABILITY_CONFIG_PERSISTENCE,
    EP_PLATFORM_CAPABILITY_LOG,
    EP_PLATFORM_CAPABILITY_THREAD,
    EP_PLATFORM_CAPABILITY_LVGL,
    EP_PLATFORM_CAPABILITY_DISPLAY,
    EP_PLATFORM_CAPABILITY_TOUCH,
    EP_PLATFORM_CAPABILITY_GPIO,
    EP_PLATFORM_CAPABILITY_I2C,
    EP_PLATFORM_CAPABILITY_SPI,
    EP_PLATFORM_CAPABILITY_UART,
    EP_PLATFORM_CAPABILITY_PWM,
    EP_PLATFORM_CAPABILITY_ADC,
    EP_PLATFORM_CAPABILITY_RTC,
    EP_PLATFORM_CAPABILITY_NETWORK,
    EP_PLATFORM_CAPABILITY_COUNT
} ep_platform_capability_e;

int ep_platform_has_capability(ep_platform_capability_e capability);
const char *ep_platform_capability_name(ep_platform_capability_e capability);

#endif
