set(EP_LVGL_PACKAGE "host_macos" CACHE STRING "LVGL prebuilt package name")

if(NOT DEFINED EP_PROJECT_ROOT)
  set(EP_PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
endif()

get_filename_component(EP_PROJECT_ROOT "${EP_PROJECT_ROOT}" ABSOLUTE)

set(EP_LVGL_ROOT "${EP_PROJECT_ROOT}/third_party/prebuilt/lvgl/${EP_LVGL_PACKAGE}")
set(EP_LVGL_INCLUDE_DIR "${EP_LVGL_ROOT}/include")
set(EP_LVGL_LIBRARY "${EP_LVGL_ROOT}/lib/liblvgl.a")
set(EP_LVGL_DEMOS_LIBRARY "${EP_LVGL_ROOT}/lib/liblvgl_demos.a")
set(EP_LVGL_MANIFEST "${EP_LVGL_ROOT}/lvgl_package.txt")

if(NOT EXISTS "${EP_LVGL_MANIFEST}")
  message(FATAL_ERROR "LVGL manifest not found: ${EP_LVGL_MANIFEST}")
endif()

if(NOT EXISTS "${EP_LVGL_INCLUDE_DIR}/lvgl.h")
  message(FATAL_ERROR "LVGL header not found: ${EP_LVGL_INCLUDE_DIR}/lvgl.h")
endif()

if(NOT EXISTS "${EP_LVGL_INCLUDE_DIR}/lv_conf.h")
  message(FATAL_ERROR "LVGL config not found: ${EP_LVGL_INCLUDE_DIR}/lv_conf.h")
endif()

if(NOT EXISTS "${EP_LVGL_LIBRARY}")
  message(FATAL_ERROR "LVGL static library not found: ${EP_LVGL_LIBRARY}")
endif()

file(READ "${EP_LVGL_MANIFEST}" EP_LVGL_MANIFEST_TEXT)
if(NOT EP_LVGL_MANIFEST_TEXT MATCHES "lvgl.version=9\\.1\\.")
  message(FATAL_ERROR "LVGL package must use LVGL 9.1.x: ${EP_LVGL_MANIFEST}")
endif()

set(EP_LVGL_INTERFACE_INCLUDE_DIRS "${EP_LVGL_INCLUDE_DIR}")
set(EP_LVGL_INTERFACE_COMPILE_OPTIONS "")
set(EP_LVGL_INTERFACE_LINK_OPTIONS "")
set(EP_LVGL_ENABLE_SDL2_BACKEND OFF)

if(EP_LVGL_MANIFEST_TEXT MATCHES "display_backend=sdl2" OR EP_LVGL_MANIFEST_TEXT MATCHES "input_backend=sdl2")
  if(APPLE AND CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
    set(EP_LVGL_ENABLE_SDL2_BACKEND ON)
  endif()
endif()

if(EP_LVGL_ENABLE_SDL2_BACKEND)
  find_program(EP_SDL2_CONFIG_EXECUTABLE sdl2-config REQUIRED)

  execute_process(COMMAND ${EP_SDL2_CONFIG_EXECUTABLE} --cflags
    OUTPUT_VARIABLE EP_SDL2_CFLAGS
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  execute_process(COMMAND ${EP_SDL2_CONFIG_EXECUTABLE} --prefix
    OUTPUT_VARIABLE EP_SDL2_PREFIX
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  execute_process(COMMAND ${EP_SDL2_CONFIG_EXECUTABLE} --libs
    OUTPUT_VARIABLE EP_SDL2_LIBS
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  separate_arguments(EP_SDL2_CFLAGS_LIST NATIVE_COMMAND "${EP_SDL2_CFLAGS}")
  separate_arguments(EP_SDL2_LIBS_LIST NATIVE_COMMAND "${EP_SDL2_LIBS}")
  set(EP_SDL2_INCLUDE_DIR "${EP_SDL2_PREFIX}/include")

  list(APPEND EP_LVGL_INTERFACE_INCLUDE_DIRS "${EP_SDL2_INCLUDE_DIR}")
  list(APPEND EP_LVGL_INTERFACE_COMPILE_OPTIONS ${EP_SDL2_CFLAGS_LIST})
  list(APPEND EP_LVGL_INTERFACE_LINK_OPTIONS ${EP_SDL2_LIBS_LIST})
endif()

set(EP_LVGL_HAS_DEMOS OFF)
if(EXISTS "${EP_LVGL_DEMOS_LIBRARY}" AND EP_LVGL_MANIFEST_TEXT MATCHES "demo_widgets=enabled")
  set(EP_LVGL_HAS_DEMOS ON)
endif()

if(NOT TARGET ep_thirdparty_lvgl)
  add_library(ep_thirdparty_lvgl STATIC IMPORTED GLOBAL)
  set_target_properties(ep_thirdparty_lvgl PROPERTIES
    IMPORTED_LOCATION "${EP_LVGL_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${EP_LVGL_INTERFACE_INCLUDE_DIRS}"
    INTERFACE_COMPILE_OPTIONS "${EP_LVGL_INTERFACE_COMPILE_OPTIONS}"
    INTERFACE_LINK_OPTIONS "${EP_LVGL_INTERFACE_LINK_OPTIONS}"
  )
endif()

if(EP_LVGL_HAS_DEMOS AND NOT TARGET ep_thirdparty_lvgl_demos)
  add_library(ep_thirdparty_lvgl_demos STATIC IMPORTED GLOBAL)
  set_target_properties(ep_thirdparty_lvgl_demos PROPERTIES
    IMPORTED_LOCATION "${EP_LVGL_DEMOS_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${EP_LVGL_INTERFACE_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES ep_thirdparty_lvgl
  )
endif()
